[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#4A90E2"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#000000"
font = "monospace"
